# Part of Odoo. See LICENSE file for full copyright and licensing details.

"""CRM lead generation from chatter messages using AI.

Inherits ``crm.lead`` to add a method that analyses an e-mail thread and
automatically creates a new CRM opportunity with AI-extracted data.
"""

import json
import logging

from odoo import _, api, fields, models
from odoo.exceptions import UserError

from ..services.decorators import ai_feature
from ..services.encryption import decrypt_api_key
from ..services.prompts import LEAD_EXTRACT_SYSTEM_PROMPT, LEAD_EXTRACT_USER_PROMPT
from ..services.providers.base import AIProviderError
from ..services.providers.factory import AIProviderFactory

_logger = logging.getLogger(__name__)


class CrmLead(models.Model):
    _inherit = "crm.lead"

    ai_generated = fields.Boolean(
        string="Generated by AI",
        default=False,
        readonly=True,
        help="Indicates this lead was created by the AI assistant.",
    )

    # ------------------------------------------------------------------
    # Public action (called from any mail.thread record)
    # ------------------------------------------------------------------

    @api.model
    @ai_feature("lead_generation")
    def action_ai_create_lead_from_thread(self, source_model, source_id):
        """Analyse a chatter thread and create a CRM lead.

        Args:
            source_model: ``_name`` of the record whose chatter to analyse.
            source_id: Database id of the source record.

        Returns:
            dict with ``content``, ``tokens_used`` and ``lead_id``.
        """
        source = self.env[source_model].browse(source_id)
        if not source.exists():
            raise UserError(_("Source record not found."))

        # 1. Collect messages -------------------------------------------
        messages_text = source._ai_collect_messages(10)
        if not messages_text:
            raise UserError(
                _("There are no messages to analyse for lead generation.")
            )

        # 2. Build prompt -----------------------------------------------
        ai_messages = [
            {"role": "system", "content": LEAD_EXTRACT_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": LEAD_EXTRACT_USER_PROMPT.format(
                    messages=messages_text
                ),
            },
        ]

        # 3. Call AI ----------------------------------------------------
        provider, model, kwargs = source._ai_get_provider_and_params()
        # Cap max_tokens to 500 for lead extraction (prevents long rambling)
        kwargs["max_tokens"] = min(kwargs.get("max_tokens", 1024), 500)
        _logger.info(
            "AI Lead: Requesting opportunity extraction from %s via %s (model=%s)...",
            source_model, provider.name, model
        )
        try:
            result = provider.chat_completion(
                ai_messages, model, **kwargs
            )
        except AIProviderError as exc:
            raise UserError(str(exc)) from exc

        # 4. Parse structured JSON from AI response --------------------
        lead_data = self._ai_parse_lead_json(result.get("content", ""))

        # 5. Create the CRM lead ----------------------------------------
        lead_vals = {
            "name": lead_data.get("opportunity_title", _("AI-generated lead")),
            "contact_name": lead_data.get("contact_name", ""),
            "partner_name": lead_data.get("company_name", ""),
            "expected_revenue": lead_data.get("expected_revenue") or 0.0,
            "description": lead_data.get("description", ""),
            "type": "opportunity",
            "ai_generated": True,
        }
        if source_model == "res.partner":
            lead_vals["partner_id"] = source.id
            if hasattr(source, "email") and source.email:
                lead_vals["email_from"] = source.email
            if hasattr(source, "phone") and source.phone:
                lead_vals["phone"] = source.phone

        lead = self.create(lead_vals)
        _logger.info("AI created CRM lead #%s from %s(%s)", lead.id, source_model, source_id)

        result["lead_id"] = lead.id
        return result

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @api.model
    def _ai_parse_lead_json(self, raw_content):
        """Extract a JSON object from the AI response text.

        Handles reasoning models (<think>...</think>), markdown fences,
        and conversational preamble/postamble.
        """
        import re

        text = raw_content.strip()
        # 1. Strip reasoning/think tags (e.g. DeepSeek-R1)
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()

        # 2. Extract from markdown code fences if present
        if "```" in text:
            match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.DOTALL)
            if match:
                text = match.group(1).strip()
            else:
                lines = [l for l in text.splitlines() if not l.strip().startswith("```")]
                text = "\n".join(lines).strip()

        # 3. Find outermost JSON object { ... }
        if not text.startswith("{"):
            brace_start = text.find("{")
            brace_end = text.rfind("}")
            if brace_start != -1 and brace_end != -1 and brace_end > brace_start:
                text = text[brace_start : brace_end + 1]

        try:
            return json.loads(text)
        except (json.JSONDecodeError, TypeError):
            _logger.warning(
                "AI did not return valid JSON for lead extraction: %s",
                raw_content[:200],
            )
            return {
                "opportunity_title": _("AI-generated lead"),
                "description": raw_content,
            }
